<?xml version="1.0" encoding="UTF-8"?>
<MethodPresentation classId="FM" formatVersion="1.2" shortName="XXX_XML_XSD_TEST">
    <Properties>
        <Default>true</Default>
        <Hotkey>Alt+T</Hotkey>
        <RunMonitor>true</RunMonitor>
        <UserDriven>true</UserDriven>
        <ValidateOnLoadForm>ClientServer</ValidateOnLoadForm>
    </Properties>
    <Parameters/>
    <Variables/>
    <Controls>
        <Form>
            <Properties>
                <Caption>XXX. Пример операции проверки соответствия xml схеме xsd</Caption>
                <Height>41</Height>
                <Left>0</Left>
                <TabIndex>0</TabIndex>
                <Top>0</Top>
                <ValidateName>Form1</ValidateName>
                <Width>321</Width>
            </Properties>
            <Controls>
                <Button>
                    <Properties>
                        <Caption>OK</Caption>
                        <Height>24</Height>
                        <Left>8</Left>
                        <Qualifier>OK</Qualifier>
                        <TabIndex>1</TabIndex>
                        <Tips>Выполнить операцию</Tips>
                        <Top>8</Top>
                        <ValidateName>Ok</ValidateName>
                        <Width>144</Width>
                    </Properties>
                </Button>
                <Button>
                    <Properties>
                        <Caption>Отмена</Caption>
                        <Height>24</Height>
                        <Left>160</Left>
                        <Qualifier>CANCEL</Qualifier>
                        <TabIndex>2</TabIndex>
                        <Tips>Отказ от выполнения</Tips>
                        <Top>8</Top>
                        <ValidateName>Cancel</ValidateName>
                        <Width>144</Width>
                    </Properties>
                </Button>
            </Controls>
        </Form>
    </Controls>
</MethodPresentation>
